<?php
//Skins
$skins_options = array(
		'default' => array(
				'options' => "a:44:{i:0;b:0;s:18:\"nav_menu_locations\";a:2:{s:9:\"menu_main\";i:16;s:11:\"menu_footer\";i:57;}s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:18:\"header-custom-1132\";s:12:\"footer_style\";s:17:\"footer-custom-735\";s:9:\"copyright\";s:50:\"Copyright © {Y} by ThemeREX. All rights reserved.\";s:19:\"load_fonts-3-family\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"menu_scheme\";s:4:\"dark\";s:19:\"boxed_bg_image_cars\";s:0:\"\";s:22:\"boxed_bg_image_courses\";s:0:\"\";s:21:\"boxed_bg_image_dishes\";s:0:\"\";s:24:\"boxed_bg_image_portfolio\";s:0:\"\";s:25:\"boxed_bg_image_properties\";s:0:\"\";s:23:\"boxed_bg_image_services\";s:0:\"\";s:20:\"boxed_bg_image_sport\";s:0:\"\";s:19:\"boxed_bg_image_team\";s:0:\"\";s:19:\"logo_retina_enabled\";s:1:\"1\";s:11:\"custom_logo\";i:707;s:11:\"logo_retina\";s:69:\"http://nelson.themerex.net/wp-content/uploads/2019/04/retina-logo.png\";s:15:\"shop_pagination\";s:5:\"pages\";s:19:\"boxed_bg_image_shop\";s:0:\"\";s:11:\"footer_type\";s:6:\"custom\";s:18:\"sidebar_style_blog\";s:7:\"inherit\";s:20:\"sidebar_style_single\";s:7:\"inherit\";s:18:\"sidebar_style_shop\";s:7:\"inherit\";s:25:\"sidebar_style_single_shop\";s:7:\"inherit\";s:22:\"sidebar_style_services\";s:7:\"inherit\";s:29:\"sidebar_style_single_services\";s:7:\"inherit\";s:18:\"sidebar_style_team\";s:7:\"inherit\";s:25:\"sidebar_style_single_team\";s:7:\"inherit\";s:23:\"sidebar_position_single\";s:7:\"inherit\";s:31:\"sidebar_widgets_single_services\";s:15:\"sidebar_widgets\";s:30:\"expand_content_single_services\";s:1:\"0\";s:32:\"sidebar_position_single_services\";s:5:\"right\";s:11:\"logo_mobile\";s:63:\"http://nelson.themerex.net/wp-content/uploads/2019/05/Logo1.png\";s:18:\"logo_mobile_retina\";s:76:\"http://nelson.themerex.net/wp-content/uploads/2019/05/Logo1retina-300x78.png\";s:11:\"header_type\";s:6:\"custom\";s:21:\"sidebar_position_team\";s:7:\"inherit\";s:28:\"sidebar_position_single_team\";s:4:\"hide\";s:22:\"sidebar_widgets_mobile\";s:7:\"inherit\";s:28:\"sidebar_position_single_shop\";s:4:\"hide\";s:10:\"meta_parts\";s:79:\"date=1|categories=1|comments=1|views=0|likes=0|author=0|share=0|edit=0|rating=0\";}"
				),
		'hair' => array(
				'options' => "a:44:{i:0;b:0;s:18:\"nav_menu_locations\";a:2:{s:9:\"menu_main\";i:16;s:11:\"menu_footer\";i:57;}s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:18:\"header-custom-1132\";s:12:\"footer_style\";s:17:\"footer-custom-735\";s:9:\"copyright\";s:50:\"Copyright © {Y} by ThemeREX. All rights reserved.\";s:19:\"load_fonts-3-family\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"menu_scheme\";s:4:\"dark\";s:19:\"boxed_bg_image_cars\";s:0:\"\";s:22:\"boxed_bg_image_courses\";s:0:\"\";s:21:\"boxed_bg_image_dishes\";s:0:\"\";s:24:\"boxed_bg_image_portfolio\";s:0:\"\";s:25:\"boxed_bg_image_properties\";s:0:\"\";s:23:\"boxed_bg_image_services\";s:0:\"\";s:20:\"boxed_bg_image_sport\";s:0:\"\";s:19:\"boxed_bg_image_team\";s:0:\"\";s:19:\"logo_retina_enabled\";s:1:\"1\";s:11:\"custom_logo\";i:707;s:11:\"logo_retina\";s:69:\"http://nelson.themerex.net/wp-content/uploads/2019/04/retina-logo.png\";s:15:\"shop_pagination\";s:5:\"pages\";s:19:\"boxed_bg_image_shop\";s:0:\"\";s:11:\"footer_type\";s:6:\"custom\";s:18:\"sidebar_style_blog\";s:7:\"inherit\";s:20:\"sidebar_style_single\";s:7:\"inherit\";s:18:\"sidebar_style_shop\";s:7:\"inherit\";s:25:\"sidebar_style_single_shop\";s:7:\"inherit\";s:22:\"sidebar_style_services\";s:7:\"inherit\";s:29:\"sidebar_style_single_services\";s:7:\"inherit\";s:18:\"sidebar_style_team\";s:7:\"inherit\";s:25:\"sidebar_style_single_team\";s:7:\"inherit\";s:23:\"sidebar_position_single\";s:7:\"inherit\";s:31:\"sidebar_widgets_single_services\";s:15:\"sidebar_widgets\";s:30:\"expand_content_single_services\";s:1:\"0\";s:32:\"sidebar_position_single_services\";s:5:\"right\";s:11:\"logo_mobile\";s:63:\"http://nelson.themerex.net/wp-content/uploads/2019/05/Logo1.png\";s:18:\"logo_mobile_retina\";s:76:\"http://nelson.themerex.net/wp-content/uploads/2019/05/Logo1retina-300x78.png\";s:11:\"header_type\";s:6:\"custom\";s:21:\"sidebar_position_team\";s:7:\"inherit\";s:28:\"sidebar_position_single_team\";s:4:\"hide\";s:22:\"sidebar_widgets_mobile\";s:7:\"inherit\";s:28:\"sidebar_position_single_shop\";s:4:\"hide\";s:10:\"meta_parts\";s:79:\"date=1|categories=1|comments=1|views=0|likes=0|author=0|share=0|edit=0|rating=0\";}"
				)
		);
?>